language: node_js
node_js:
- 8.9.0
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    rooms:
      secure: Jhs7/Yhm1JdRU/gCY4c1GOcSaDo+04K0H0aYnw2EaOvkuiCtpa5z6IeTk2B1LzY8YGFR//ELP/cVyTG5xScFu30ZFaVazD6Xq8ZXEU99Tm6DAhw6MWNDu5uq8NMDU39QmB/Y/66pXjXO+3Cuua0Ag3IB6F0wrQUEKu50v6E+TaitzECKJE+gTkKABhGqwzxv+6tMiIzYkwoG5zEQo6hl+VICcNtoMeIFn54xAcBO7bWZ/lWU0PMtlMJaGBLJIRpKzpGF4N+0ATqgJfmLUXMkdi4ZV5aEfnCRf22L4lvOjTHkA6jZmrjRtwaPBOmLYDvTdQS9woFLqxeqKjh+a8PPh1nMkvcOoRrU+hj8cfeL1nz2KtWNfUj7TE+jHXMtiYBePKSjMm2gSaObUnTL9PDX1pBcfHH3XKKN0ths84gtB/wxfv4u8t3VxMKav+35YGflu7zYSByyivtqCWya6dzWXYbrT5hgdcFfPqS5TuoL3EjCHS6+25q1oBv9Y9OQs1IHOXZBkbrwu1qJW6xALi6yw3iWvBECwYHdx8mN6OCQFI240YiTGoOKfgFHD7eRLK9d5pGEkKFSJr5Vr37fSlkv+XnYPqewL0925ug2lEMzn9X4kuqnfesyN7q/P+TnWDqZS9RhMBOgFDEVXnoLiw2mH8agMUgg72F2sI8fDuFINYI=
    on_success: never
    on_failure: always
    on_pull_requests: false
install:
- npm install
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- npm prune
- greenkeeper-lockfile-update
after_success:
- npm run coveralls
- npm run semantic-release
after_script:
- greenkeeper-lockfile-upload
